steps:

# build generator  
- id: build_generator
  name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'generator'
- id: dockerize_generator
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lofty-totality-214401/kgen', '.']
  dir: 'generator'

# build examples
- id: example_key
  name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=sa.json.enc
    - --plaintext-file=app/src/main/res/raw/sa.json
    - --location=global
    - --keyring=build-keyring
    - --key=build-key
  dir: 'examples'
  waitFor: ['-']
- id: examples_builder
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.android', '-t', 'example-builder', '.']
  dir: 'examples'
  waitFor: ['-']
- id: build_examples
  name: 'example-builder'
  args: []
  dir: 'examples'
  waitFor:
    - examples_builder

# run example tests
# - id: examples_tester
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ["firebase", "test", "android", "run", "--app", "app/build/outputs/apk/debug/app-debug.apk", "--test", "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"]
#   dir: 'examples'
#   waitFor:
#     - build_examples

# spin up showcase server and run tests
- id: start_showcase
  name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  dir: 'showcase-test'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'showcase-test'
  env:
  - 'HOST=showcase'
  - 'PORT=7469'
  waitFor: 
    - start_showcase
    - build_generator

timeout: 1200s
