steps:

# checkout submodules
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'init']
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--remote']

# build generator  
- id: build_generator
  name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'generator'
- id: dockerize_generator
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kotlin-gapic/kgen', '.']
  dir: 'generator'

# build examples
- id: example_key
  name: 'ubuntu'
  args: ['bash', '-c', 'touch app/src/main/res/raw/sa.json']
  dir: 'examples'
  waitFor: ['-']
- id: build_examples
  name: 'gcr.io/kotlin-gapic/example-builder'
  args: []
  dir: 'examples'
  waitFor:
    - build_generator
    - example_key

# TODO:
# run example tests
# - id: examples_tester
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ["firebase", "test", "android", "run", "--app", "app/build/outputs/apk/debug/app-debug.apk", "--test", "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"]
#   dir: 'examples'
#   waitFor:
#     - build_examples

# spin up showcase server and run tests
- id: start_showcase
  name: 'docker/compose:1.15.0'
  args: ['up', '-d']
  dir: 'showcase-test'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'showcase-test'
  env:
  - 'HOST=showcase'
  - 'PORT=7469'
  waitFor: 
    - start_showcase
    - build_generator

images: ['gcr.io/kotlin-gapic/kgen']

timeout: 1200s
